In [32]:
import pandas as pd
import numpy as np

In [33]:
fb = pd.read_csv('/home/student/Downloads/dataset_Facebook(1).csv', sep =';')
fb

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [34]:
fb.shape

(500, 19)

In [35]:
fb.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [36]:
fb.median(numeric_only = True)

Page total likes                                                       129600.0
Category                                                                    2.0
Post Month                                                                  7.0
Post Weekday                                                                4.0
Post Hour                                                                   9.0
Paid                                                                        0.0
Lifetime Post Total Reach                                                5281.0
Lifetime Post Total Impressions                                          9051.0
Lifetime Engaged Users                                                    625.5
Lifetime Post Consumers                                                   551.5
Lifetime Post Consumptions                                                851.0
Lifetime Post Impressions by people who have liked your Page             6255.5
Lifetime Post reach by people who like your Page                         3417.0
Lifetime People who have liked your Page and engaged with your post       412.0
comment                                                                     3.0
like                                                                      101.0
share                                                                      19.0
Total Interactions                                                        123.5
dtype: float64

In [37]:
fb.mean(numeric_only = True)

Page total likes                                                       123194.176000
Category                                                                    1.880000
Post Month                                                                  7.038000
Post Weekday                                                                4.150000
Post Hour                                                                   7.840000
Paid                                                                        0.278557
Lifetime Post Total Reach                                               13903.360000
Lifetime Post Total Impressions                                         29585.948000
Lifetime Engaged Users                                                    920.344000
Lifetime Post Consumers                                                   798.772000
Lifetime Post Consumptions                                               1415.130000
Lifetime Post Impressions by people who have liked your Page            16766.376000
Lifetime Post reach by people who like your Page                         6585.488000
Lifetime People who have liked your Page and engaged with your post       609.986000
comment                                                                     7.482000
like                                                                      177.945892
share                                                                      27.266129
Total Interactions                                                        212.120000
dtype: float64

In [38]:
fb.mode()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,136393.0,Photo,1.0,10.0,7.0,3.0,0.0,677.0,4372.0,537.0,182.0,431.0,1210.0,690,403.0,0.0,98.0,13.0,0.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2232.0,6503.0,NaN,298.0,513.0,1284.0,704,NaN,NaN,NaN,14.0,39.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2645.0,7004.0,NaN,319.0,599.0,2541.0,1228,NaN,NaN,NaN,NaN,75.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2938.0,8533.0,NaN,322.0,652.0,2888.0,1640,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3322.0,8745.0,NaN,335.0,719.0,3675.0,1674,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3358.0,12735.0,NaN,374.0,730.0,4911.0,1722,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3414.0,NaN,NaN,482.0,795.0,4935.0,2044,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3528.0,NaN,NaN,503.0,889.0,5010.0,2124,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3754.0,NaN,NaN,513.0,NaN,5732.0,2162,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5280.0,NaN,NaN,642.0,NaN,NaN,2174,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5290.0,NaN,NaN,NaN,NaN,NaN,2388,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6692.0,NaN,NaN,NaN,NaN,NaN,2426,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9528.0,NaN,NaN,NaN,NaN,NaN,2604,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13544.0,NaN,NaN,NaN,NaN,NaN,2616,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32208.0,NaN,NaN,NaN,NaN,NaN,2644,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2660,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2704,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2752,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2868,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3114,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3216,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3230,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3298,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3768,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5348,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5372,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7020,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7800,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8032,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8120,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20608,NaN,NaN,NaN,NaN,NaN

In [39]:
fb.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [40]:
fb.isna()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False

In [45]:
fb["Paid"] = fb["Paid"].fillna(fb["Paid"].mode()[0])
fb["share"] = fb['share'].fillna(fb["share"].mode()[0])
fb["like"] = fb["like"].fillna(fb["like"].mode()[0])

In [46]:
fb.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   0
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   0
share                                                                  0
Total Interactions                                                     0
dtype: int64

In [47]:
subset1 = fb[fb["Category"]==2]
subset1

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467,91758,Photo,2,2,5,3,1.0,15880,51571,1188,1071,1410,47976,13560,677,1,200.0,37.0,238
480,86909,Photo,2,1,4,11,0.0,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
483,86491,Photo,2,1,3,3,0.0,5526,8779,1096,1058,1399,5732,3412,453,2,69.0,26.0,97
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
499,81370,Photo,2,1,4,4,0.0,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [55]:
subset2 = fb[(fb["Post Hour"] == 10) & (fb["Category"] == 1)]
subset2

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
37,138895,Photo,1,12,7,10,1.0,19800,28663,479,424,805,5187,2752,248,16,76.0,8.0,100
42,138353,Photo,1,12,5,10,0.0,7268,13989,2087,2079,12074,13544,7096,1975,7,26.0,3.0,36
54,138329,Photo,1,11,6,10,0.0,2425,4462,260,213,433,3017,1510,175,4,66.0,13.0,83
58,138329,Photo,1,11,4,10,0.0,2257,4372,230,173,327,3188,1557,168,3,76.0,11.0,90
62,138185,Photo,1,11,2,10,1.0,28752,47358,802,654,1268,14091,7456,408,10,179.0,13.0,202
64,138185,Photo,1,11,1,10,0.0,2352,5234,232,182,258,4101,1761,181,2,60.0,7.0,69
70,137893,Photo,1,11,5,10,1.0,39344,103050,588,460,695,39304,11392,336,7,146.0,9.0,162
77,137177,Photo,1,11,1,10,0.0,22984,59040,438,374,542,12716,4968,262,4,85.0,8.0,97
99,137020,Photo,1,10,4,10,0.0,12776,21893,785,539,881,13272,7800,575,12,328.0,90.0,430
110,136736,Photo,1,10,6,10,0.0,1673,3655,338,324,1619,2598,1469,268,2,28.0,4.0,34
118,136642,Photo,1,10,7,10,0.0,834,1570,399,392,510,1390,704,351,0,7.0,2.0,9
119,136393,Photo,1,10,7,10,0.0,786,1573,263,257,318,1401,660,222,0,6.0,2.0,8
136,136393,Link,1,10,5,10,0.0,4664,9463,204,182,251,7196,3324,173,0,32.0,16.0,48
139,136013,Photo,1,10,4,10,1.0,4018,8617,428,374,616,6677,2992,351,4,77.0,19.0,100
145,136013,Photo,1,10,1,10,1.0,5324,11040,528,483,861,8627,4054,448,6,76.0,14.0,96
153,135713,Photo,1,10,4,10,0.0,8612,20151,813,727,1390,16890,7208,630,7,161.0,25.0,193
164,135428,Photo,1,9,5,10,0.0,1060,2004,266,251,337,1705,870,204,0,18.0,13.0,18
166,135428,Photo,1,9,4,10,1.0,13856,37716,519,450,672,26832,9064,389,2,77.0,5.0,84
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
181,134879,Photo,1,9,3,10,0.0,14152,38806,631,549,836,19409,6632,404,4,102.0,8.0,114
183,134879,Video,1,9,2,10,0.0,30624,56950,2080,1956,3253,32033,15744,1376,6,345.0,121.0,472
185,134879,Photo,1,9,1,10,0.0,2232,4005,374,335,458,3247,1740,278,0,62.0,10.0,72
215,131956,Photo,1,8,3,10,0.0,28880,64746,1062,991,1971,40181,15808,740,2,114.0,10.0,126
227,131728,Photo,1,7,4,10,1.0,95424,252207,699,575,882,78287,22016,417,6,109.0,11.0,126
271,128032,Photo,1,7,3,10,1.0,66976,111502,1191,1054,1641,40203,19968,708,7,215.0,47.0,269
339,117764,Photo,1,5,4,10,0.0,18056,32576,1062,875,1389,26514,14728,701,25,307.0,58.0,390
417,104070,Photo,1,3,3,10,0.0,1874,2474,25,25,31,1483,1062,15,0,0.0,0.0,0
418,102112,Photo,1,3,3,10,0.0,4122,7073,466,455,609,5827,3302,361,1,27.0,11.0,39
437,100732,Photo,1,3,6,10,0.0,122944,457509,1373,1268,2106,72846,13184,475,0,136.0,13.0,149
440,98195,Photo,1,3,5,10,0.0,4118,7355,546,526,675,6423,3466,379,1,28.0,7.0,36
447,96749,Photo,1,3,7,10,1.0,7220,12735,2348,2300,3311,9837,5296,642,6,88.0,24.0,118
476,86909,Photo,1,1,6,10,1.0,37088,10966,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633

In [57]:
subset3 = fb[fb["Lifetime Post Consumers"] > 600]
subset3

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,85979,Photo,3,1,6,3,1.0,6184,10228,956,901,1140,6085,3502,437,1,105.0,46.0,152
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137
493,85093,Photo,3,1,1,2,0.0,8412,13960,1179,1111,1632,8632,5348,699,17,185.0,55.0,257
494,85093,Photo,3,1,7,10,0.0,5400,9218,810,756,1003,5654,3230,422,10,125.0,41.0,176
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84

In [62]:
subset4 = fb.iloc[1:6]
subset4

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186

In [60]:
subset5 = fb.iloc[1:6, 0:5]
subset5

   Page total likes    Type  Category  Post Month  Post Weekday
1            139441  Status         2          12             3
2            139441   Photo         3          12             3
3            139441   Photo         2          12             2
4            139441   Photo         2          12             2
5            139441  Status         2          12             1

In [64]:
subset6 = fb[fb["like"] > 100]
subset6

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,85979,Photo,3,1,7,10,0.0,9700,17442,1407,1271,2007,8872,4876,660,21,277.0,80.0,378
491,85979,Photo,3,1,6,3,1.0,6184,10228,956,901,1140,6085,3502,437,1,105.0,46.0,152
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137
493,85093,Photo,3,1,1,2,0.0,8412,13960,1179,1111,1632,8632,5348,699,17,185.0,55.0,257
494,85093,Photo,3,1,7,10,0.0,5400,9218,810,756,1003,5654,3230,422,10,125.0,41.0,176

In [68]:
subset7 = fb[(fb["share"]> 20) & (fb["comment"] > 15)]
subset7

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
30,138895,Photo,2,12,4,2,0.0,4940,9390,385,306,501,5860,2930,273,33,107.0,22.0,162
51,138329,Photo,1,11,1,3,1.0,25248,40125,726,467,863,16132,8608,451,24,285.0,28.0,337
65,138185,Photo,1,11,1,3,0.0,3416,6167,356,298,641,4530,2388,280,19,77.0,23.0,119
67,138185,Photo,1,11,7,3,1.0,53456,93790,1576,995,1469,32646,14912,884,20,697.0,70.0,787
71,137893,Video,1,11,5,3,1.0,100768,220447,2101,1735,2331,59658,18880,885,17,449.0,84.0,550
75,137893,Photo,1,11,3,2,1.0,37376,68610,1150,808,1341,22100,10880,724,20,411.0,74.0,505
81,137177,Photo,3,11,6,10,0.0,5990,11123,657,361,512,5057,2628,428,18,370.0,53.0,441
101,137020,Photo,2,10,4,3,0.0,68896,104952,2624,1326,1952,35707,19840,1354,26,1505.0,95.0,1626
105,137020,Photo,1,10,2,4,0.0,70144,111745,3216,2628,4782,43671,20608,1542,42,955.0,139.0,1136
107,136736,Status,2,10,1,4,0.0,9504,19556,1132,1032,1512,16018,7616,981,17,193.0,28.0,238
142,136013,Status,2,10,3,2,1.0,31136,59964,6164,5934,9237,35977,18048,4376,60,859.0,90.0,1009
150,135713,Photo,1,10,6,4,0.0,39984,112830,2105,1921,3932,70249,21328,1609,24,302.0,41.0,367
152,135713,Photo,2,10,5,4,1.0,6564,12097,806,602,957,7682,4024,563,47,358.0,49.0,454
156,135700,Photo,2,9,2,11,0.0,3756,7094,469,408,613,4935,2556,365,16,117.0,30.0,163
158,135700,Photo,2,9,1,10,0.0,5086,9493,622,509,757,6200,3298,489,30,187.0,35.0,252
162,135617,Photo,3,9,6,10,0.0,7512,13633,769,614,951,5503,3260,530,22,290.0,98.0,410
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
172,135195,Status,2,9,1,10,0.0,21256,41906,4840,4754,5906,35455,17592,4318,38,163.0,27.0,228
176,135195,Photo,3,9,6,3,1.0,22304,37159,1805,984,1618,22864,13304,1349,29,1047.0,98.0,1174
180,134879,Status,2,9,4,4,1.0,9124,17776,1476,1397,1797,13887,7092,1331,20,150.0,29.0,199
199,132817,Photo,3,8,4,10,0.0,33536,64850,1954,1016,1678,50076,24448,1564,33,1155.0,102.0,1290
219,131956,Photo,3,8,1,12,0.0,5746,9874,769,632,1063,7407,4288,584,16,227.0,28.0,271
223,131808,Status,2,8,6,10,1.0,20168,35904,3370,3244,5106,26881,15056,2806,18,332.0,54.0,404
228,131728,Photo,2,7,4,3,0.0,14824,21863,868,591,966,13498,8560,650,64,367.0,25.0,456
243,130791,Video,1,7,3,11,1.0,21872,40413,3872,3822,7327,24667,12920,2218,18,315.0,76.0,409
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
272,127082,Photo,1,7,3,3,1.0,76096,94644,2889,2495,4596,31096,19744,1276,22,534.0,31.0,587
277,126424,Video,1,6,2,13,0.0,139008,277100,1779,1643,2356,107502,38720,1008,23,204.0,44.0,271
288,126141,Photo,1,6,4,12,0.0,20896,29062,1418,1038,2048,19738,13656,998,103,469.0,33.0,605
319,123047,Photo,2,6,4,5,1.0,11304,20647,1141,1065,1874,14792,7800,732,18,168.0,49.0,235
323,123047,Photo,3,6,1,10,0.0,56672,104966,2579,1334,1850,78678,37408,1831,20,1372.0,47.0,1439
328,120050,Photo,3,5,4,12,0.0,39040,55633,1684,1183,2123,32021,19712,1101,16,617.0,58.0,691
330,120050,Photo,3,5,3,12,0.0,21248,34095,1049,918,1438,11280,6664,536,20,199.0,32.0,251
338,119198,Photo,3,5,5,10,1.0,6460,11373,823,706,1197,6279,3612,505,25,244.0,44.0,313
339,117764,Photo,1,5,4,10,0.0,18056,32576,1062,875,1389,26514,14728,701,25,307.0,58.0,390
346,117764,Photo,3,5,7,2,0.0,38960,65149,2298,1702,3000,57722,34368,1978,37,821.0,90.0,948
349,117764,Photo,3,5,5,13,0.0,81856,124753,3000,1637,2718,52477,27392,1756,45,1639.0,122.0,1806
359,116091,Photo,3,5,7,2,0.0,6984,12066,780,631,1116,8188,4776,570,25,256.0,54.0,335
370,113028,Photo,1,4,6,14,0.0,28352,55202,1476,1242,1990,47899,24512,1185,45,407.0,76.0,528
371,113028,Status,2,4,6,3,1.0,17912,34774,2750,2567,6591,21009,11408,2256,17,447.0,123.0,587
379,111620,Photo,3,4,1,14,1.0,105632,147918,3984,2254,3391,48575,27328,1936,51,1998.0,128.0,2177
460,92507,Photo,3,2,1,13,0.0,55520,665792,4544,3586,6624,648611,47488,3430,146,1546.0,181.0,1873
462,92293,Photo,3,2,7,13,1.0,10040,17029,1429,1346,2022,11744,6964,742,19,214.0,78.0,311
480,86909,Photo,2,1,4,11,0.0,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
488,85979,Photo,3,1,7,10,0.0,9700,17442,1407,1271,2007,8872,4876,660,21,277.0,80.0,378
493,85093,Photo,3,1,1,2,0.0,8412,13960,1179,1111,1632,8632,5348,699,17,185.0,55.0,257

In [71]:
merge1 = pd.concat([subset4 , subset5])
merge1

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10.0,0.0,10460.0,19057.0,1457.0,1361.0,1674.0,11710.0,6112.0,1108.0,5.0,130.0,29.0,164.0
2,139441,Photo,3,12,3,3.0,0.0,2413.0,4373.0,177.0,113.0,154.0,2812.0,1503.0,132.0,0.0,66.0,14.0,80.0
3,139441,Photo,2,12,2,10.0,1.0,50128.0,87991.0,2211.0,790.0,1119.0,61027.0,32048.0,1386.0,58.0,1572.0,147.0,1777.0
4,139441,Photo,2,12,2,3.0,0.0,7244.0,13594.0,671.0,410.0,580.0,6228.0,3200.0,396.0,19.0,325.0,49.0,393.0
5,139441,Status,2,12,1,9.0,0.0,10472.0,20849.0,1191.0,1073.0,1389.0,16034.0,7852.0,1016.0,1.0,152.0,33.0,186.0
1,139441,Status,2,12,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,139441,Photo,3,12,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,139441,Photo,2,12,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,139441,Photo,2,12,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,139441,Status,2,12,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
merge2 = pd.merge(subset1 , subset5) 
merge2

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
1,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
2,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
3,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186

In [76]:
transposed_fb = fb.transpose()
transposed_fb

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [85]:
reshaped_fb = pd.pivot_table(fb, index = ["Category", "Post Month"], columns = ["Type"], values = ["Lifetime Post Impressions by people who have liked your Page"])
reshaped_fb

                    Lifetime Post Impressions by people who have liked your Page  \
Type                                                                        Link
Category Post Month
1        1                                                10488.500000
         2                                                13919.000000
         3                                                 3972.000000
         4                                                24783.333333
         5                                                16914.000000
         6                                                         NaN
         7                                                         NaN
         8                                                         NaN
         9                                                         NaN
         10                                                9767.000000
         11                                               13858.000000
         12                                                5439.000000
2        1                                                         NaN
         2                                                         NaN
         3                                                 8964.000000
         4                                                         NaN
         5                                                         NaN
         6                                                         NaN
         7                                                         NaN
         8                                                         NaN
         9                                                         NaN
         10                                                        NaN
         11                                                        NaN
         12                                                        NaN
3        1                                                         NaN
         2                                                         NaN
         3                                                 9403.000000
         4                                                         NaN
         5                                                         NaN
         6                                                         NaN
         7                                                         NaN
         8                                                         NaN
         9                                                         NaN
         10                                                        NaN
         11                                                        NaN
         12                                                        NaN


Type                        Photo        Status          Video
Category Post Month
1        1           35526.500000           NaN            NaN
         2           30912.909091           NaN            NaN
         3           47748.655172  13246.000000            NaN
         4           21455.000000           NaN            NaN
         5           13389.333333  37816.000000            NaN
         6           14213.277778           NaN  107502.000000
         7           20377.666667           NaN   24667.000000
         8           26369.666667           NaN            NaN
         9           12430.250000           NaN   32033.000000
         10           9271.823529           NaN            NaN
         11          12479.793103           NaN   35905.333333
         12          17228.250000  24363.000000   30131.000000
2        1            5582.000000           NaN            NaN
         2           19874.333333           NaN            NaN
         3            7034.000000           NaN            NaN
         4           15729.000000  21009.000000            NaN
         5            6120.428571  14189.000000            NaN
         6            5700.666667  14843.500000            NaN
         7           12704.562500  20488.714286            NaN
         8            3472.600000  19834.750000            NaN
         9            3809.142857  21259.000000            NaN
         10           8962.000000  20423.857143            NaN
         11           2618.250000  15418.000000            NaN
         12          11787.583333  17654.500000            NaN
3        1            6709.400000           NaN            NaN
         2           67700.727273           NaN            NaN
         3           96208.000000           NaN            NaN
         4            7796.391304           NaN            NaN
         5           11313.913043           NaN            NaN
         6            9992.157895           NaN            NaN
         7           10680.230769           NaN            NaN
         8           26314.272727           NaN            NaN
         9            7991.444444           NaN            NaN
         10           4395.000000  20547.000000            NaN
         11           4424.200000   8555.500000            NaN
         12           5673.818182   5009.000000            NaN

In [86]:
reshaped_fb.shape

(36, 4)