In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
cars = pd.read_csv('CAR.csv')
cars

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000.0,100000.0,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000.0,46000.0,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000.0,141000.0,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000.0,83000.0,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000.0,90000.0,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000.0,40000.0,Petrol,Individual,Manual,First Owner

In [3]:
cars.shape

(4340, 8)

In [4]:
cars.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000.0,100000.0,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000.0,46000.0,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000.0,141000.0,Diesel,Individual,Manual,Second Owner

In [5]:
cars.tail()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000.0,83000.0,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000.0,90000.0,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000.0,40000.0,Petrol,Individual,Manual,First Owner

In [6]:
cars.describe()

              year  selling_price      km_driven
count  4340.000000   4.339000e+03    4338.000000
mean   2013.090783   5.042205e+05   66243.652374
std       4.215344   5.785829e+05   46636.666295
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.100000e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [7]:
cars.dtypes

name                 str
year               int64
selling_price    float64
km_driven        float64
fuel                 str
seller_type          str
transmission         str
owner                str
dtype: object

## Data Cleaning

In [8]:
print(cars.isnull().sum())

name             0
year             0
selling_price    1
km_driven        2
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [9]:
cars.mean(numeric_only=True)

year               2013.090783
selling_price    504220.450104
km_driven         66243.652374
dtype: float64

In [10]:
cars.median(numeric_only=True)

year               2014.0
selling_price    350000.0
km_driven         60000.0
dtype: float64

In [11]:
cars.mode()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti Swift Dzire VDI,2017,300000.0,70000.0,Diesel,Individual,Manual,First Owner

In [12]:
cars['km_driven']=cars['km_driven'].fillna(cars['km_driven'].median())

In [13]:
print(cars.isnull().sum())

name             0
year             0
selling_price    1
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [14]:
cars=cars.dropna()

In [15]:
print(cars.isnull().sum())

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

## Data Transformation

In [16]:
for x in range (4,8):
    print(pd.unique(cars.iloc[:,x]),"\n")

<StringArray>
['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric']
Length: 5, dtype: str

<StringArray>
['Individual', 'Dealer', 'Trustmark Dealer']
Length: 3, dtype: str

<StringArray>
['Manual', 'Automatic']
Length: 2, dtype: str

<StringArray>
[         'First Owner',         'Second Owner', 'Fourth & Above Owner',
          'Third Owner',       'Test Drive Car']
Length: 5, dtype: str

In [17]:
print(cars.groupby('fuel')['selling_price'].mean())
print(cars.groupby('seller_type')['selling_price'].mean())
print(cars.groupby('transmission')['selling_price'].mean())
print(cars.groupby('owner')['selling_price'].mean())

fuel
CNG         277174.925000
Diesel      669094.252206
Electric    310000.000000
LPG         167826.043478
Petrol      344955.519321
Name: selling_price, dtype: float64
seller_type
Dealer              721822.890342
Individual          424605.482578
Trustmark Dealer    914950.980392
Name: selling_price, dtype: float64
transmission
Automatic    1.408154e+06
Manual       4.001438e+05
Name: selling_price, dtype: float64
owner
First Owner             598636.969633
Fourth & Above Owner    173901.197531
Second Owner            343891.088608
Test Drive Car          954293.941176
Third Owner             270033.323432
Name: selling_price, dtype: float64

In [18]:
cars['fuel']=cars['fuel'].map({'LPG':0,'CNG':1,'Electric':2,'Petrol':3,'Diesel':4})
cars['seller_type']=cars['seller_type'].map({'Individual':0,'Dealer':1,'Trustmark Dealer':2})
cars['transmission']=cars['transmission'].map({'Automatic':0,'Manual':1})
cars['owner']=cars['owner'].map({'Fourth & Above Owner':0,'Third Owner':1,'Second Owner':2,'First Owner':3,'Test Drive Car':4})
cars

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000.0,70000.0,3,0,1,3
1,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,3,0,1,3
2,Hyundai Verna 1.6 SX,2012,600000.0,100000.0,4,0,1,3
3,Datsun RediGO T Option,2017,250000.0,46000.0,3,0,1,3
4,Honda Amaze VX i-DTEC,2014,450000.0,141000.0,4,0,1,2
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999.0,80000.0,4,0,1,2
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999.0,80000.0,4,0,1,2
4337,Maruti 800 AC BSIII,2009,110000.0,83000.0,3,0,1,2
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000.0,90000.0,4,0,1,3
4339,Renault KWID RXT,2016,225000.0,40000.0,3,0,1,3

In [19]:
for x in range (4,8):
    print(pd.unique(cars.iloc[:,x]),"\n")

[3 4 1 0 2]

[0 1 2]

[1 0]

[3 2 0 1 4]

In [20]:
cars.dtypes

name                 str
year               int64
selling_price    float64
km_driven        float64
fuel               int64
seller_type        int64
transmission       int64
owner              int64
dtype: object

In [21]:
from sklearn.preprocessing import LabelEncoder
cars['name']=LabelEncoder().fit_transform(cars['name'])

In [22]:
cars.cov()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
name,1.600518e+05,-8.710457e+01,-1.793462e+07,2.356264e+06,15.033752,-17.005712,10.681078,-14.567347
year,-8.710457e+01,1.776467e+01,1.009130e+06,-8.247581e+04,0.296992,0.381872,-0.184348,1.405177
selling_price,-1.793462e+07,1.009130e+06,3.347581e+11,-5.189548e+09,91411.335279,69176.084319,-93352.289155,93859.036492
km_driven,2.356264e+06,-8.247581e+04,-5.189548e+09,2.174452e+09,6271.321825,-4319.182033,1697.642374,-10691.601507
fuel,1.503375e+01,2.969915e-01,9.141134e+04,6.271322e+03,0.367995,0.011519,-0.010648,0.009597
seller_type,-1.700571e+01,3.818718e-01,6.917608e+04,-4.319182e+03,0.011519,0.246941,-0.030269,0.091766
transmission,1.068108e+01,-1.843477e-01,-9.335229e+04,1.697642e+03,-0.010648,-0.030269,0.092610,-0.018003
owner,-1.456735e+01,1.405177e+00,9.385904e+04,-1.069160e+04,0.009597,0.091766,-0.018003,0.506777

In [23]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()


cars[['km_driven','fuel','seller_type','transmission','owner']] = scaler.fit_transform(
    cars[['km_driven','fuel','seller_type','transmission','owner']]
)

In [24]:
cars.cov()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
name,1.600518e+05,-8.710457e+01,-1.793462e+07,2.921238,3.758438,-8.502856,10.681078,-3.641837
year,-8.710457e+01,1.776467e+01,1.009130e+06,-0.102251,0.074248,0.190936,-0.184348,0.351294
selling_price,-1.793462e+07,1.009130e+06,3.347581e+11,-6433.872030,22852.833820,34588.042159,-93352.289155,23464.759123
km_driven,2.921238e+00,-1.022514e-01,-6.433872e+03,0.003342,0.001944,-0.002677,0.002105,-0.003314
fuel,3.758438e+00,7.424788e-02,2.285283e+04,0.001944,0.023000,0.001440,-0.002662,0.000600
seller_type,-8.502856e+00,1.909359e-01,3.458804e+04,-0.002677,0.001440,0.061735,-0.015135,0.011471
transmission,1.068108e+01,-1.843477e-01,-9.335229e+04,0.002105,-0.002662,-0.015135,0.092610,-0.004501
owner,-3.641837e+00,3.512943e-01,2.346476e+04,-0.003314,0.000600,0.011471,-0.004501,0.031674

In [25]:
from sklearn.model_selection import train_test_split
X = cars[["selling_price"]]
y = cars['km_driven']
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42);

In [26]:
from sklearn.linear_model import LinearRegression
pred1 = LinearRegression().fit(x_train,y_train)

In [27]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
y_pred = pred1.predict(x_test)

In [28]:
print("Mean squared error", mean_squared_error(y_test,y_pred))
print("R2 Score", r2_score(y_test,y_pred))

Mean squared error 0.0037414229279916695
R2 Score 0.026596297652998646

In [29]:
x2=cars.drop(columns=['selling_price'])
y2=cars['selling_price']

In [30]:
X2_train,X2_test,y2_train,y2_test=train_test_split(x2,y2, random_state=41, test_size=0.25)

In [31]:
model2=LinearRegression().fit(X2_train,y2_train)

In [32]:
y_pred2=model2.predict(X2_test)


mse = mean_squared_error(y2_test, y_pred2)
mae = mean_absolute_error(y2_test, y_pred2)
r2 = r2_score(y2_test, y_pred2)

print(f"Mean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"R-squared: {r2}")

Mean Squared Error: 157541757452.17822
Mean Absolute Error: 230486.52011461149
R-squared: 0.5000884060852919

## Self Prediction

In [ ]:
model = input("Enter car model")
year = int(input("Enter year of Manufacture"))
km_driven = float(input("Enter km driven"))
fuel = input("Enter fuel of car")
seller_type = input("Enter seller type")
transmission = input("Enter transmission")
owner = input("Enter owner")
input_data = pd.DataFrame({
    'name' : [model],
    'year': [year],
    'km_driven': [km_driven],
    'fuel': [fuel],
    'seller_type': [seller_type],
    'transmission': [transmission],
    'owner': [owner]
})
input_data['fuel']=input_data['fuel'].map({'LPG':0,'CNG':1,'Electric':2,'Petrol':3,'Diesel':4})
input_data['seller_type']=input_data['seller_type'].map({'Individual':0,'Dealer':1,'Trustmark Dealer':2})
input_data['transmission']=input_data['transmission'].map({'Automatic':0,'Manual':1})
input_data['owner']=input_data['owner'].map({'Fourth & Above Owner':0,'Third Owner':1,'Second Owner':2,'First Owner':3,'Test Drive Car':4})
input_data['name']=LabelEncoder().fit_transform(input_data['name'])
input_data[['km_driven','fuel','seller_type','transmission','owner']] = scaler.transform(
    input_data[['km_driven','fuel','seller_type','transmission','owner']]
)
ans=model2.predict(input_data)
print("Car price is",ans[0])

Enter car model rfr